[package]
name = "phoenix-app-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
blake3.workspace = true
hashbrown.workspace = true
phoenix-scene-archive = { path = "../phoenix-scene-archive" }
phoenix-scene-compiler = { path = "../phoenix-scene-compiler" }
phoenix-scene-contract = { path = "../phoenix-scene-contract" }
phoenix-scene-product-index = { path = "../phoenix-scene-product-index" }
phoenix-scene-publisher = { path = "../phoenix-scene-publisher" }
phoenix-workspace = { path = "../phoenix-workspace" }
thiserror.workspace = true
tracing.workspace = true
