[package]
name = "phoenix-graph-generation-v2"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
blake3.workspace = true
bytemuck.workspace = true
hashbrown.workspace = true
memmap2.workspace = true
thiserror.workspace = true

[dev-dependencies]
phoenix-graph-generation = { path = "../phoenix-graph-generation" }
